setwd("D:")
library(stats)
library(magrittr)
library(caret)
set.seed(06)
A <- read.csv("ANV.csv")
colSums(is.na(A))
B <- A[,-c(1)]
summary(A$Outlet_Identifier)
#C <- A[,c(7,11)]
install.packages("corrgram")
library(corrgram)
corrgram(B,type = NULL,order = FALSE)
#C <- ifelse(B$Outlet_Establishment_Year <= 2003,1,ifelse(B$Outlet_Establishment_Year <= 2008 ,2,3))
#C <- data.frame(C)
#B <- cbind(B,C)
#D <- B[!is.na(B$Item_Weight),]
#str(D)
library(mice)
B <- mice(B,m=5,method = "pmm")
D <- complete(B,1)
Rate_per_weight = (D$Item_Weight/D$Item_MRP)
Rate_per_weight = data.frame(Rate_per_weight)
D <- cbind(D,Rate_per_weight)
corrgram(D,type = NULL,order = FALSE)
#L <- createDataPartition(c$Item_Outlet_Sales,p = 0.9,list = FALSE) %>% c()
#train = c[L,] 
#test = c[-L,]
#model1 <- lm(Item_Outlet_Sales~Item_MRP+Item_Weight+Outlet_Identifier+Rate_per_weight,train)
#summary(model1)
#class <- predict(model1,train1)
#RMSE(class,test$Item_Outlet_Sales)
model1 <-  lm(Item_Outlet_Sales~Item_MRP+Item_Weight+Outlet_Identifier+Rate_per_weight,D)
train1 <- read.csv("Test_u94Q5KV.csv")
Rate_per_weight = (train1$Item_Weight/train1$Item_MRP)
test1 <- cbind(train1,Rate_per_weight)
library(mice)
library(e1071)
test1 <- test1[,-c(1)]
test1 <- mice(test1,m=5,method = "pmm")
b <- complete(test1,1)
Item_Outlet_Sales <- predict(model1,b,type ="response" )
View(Item_Outlet_Sales)
write.csv(Item_Outlet_Sales,"result.csv")
